language: python

addons:

matrix:
  include:
    - python: "3.7"
    - python: "3.12"

install:
  - pip install coveralls
  - make develop

before_script:

script:
  - make lint
  - make coverage

after_success:
  - coveralls
  - coverage report

notifications:
  email:
    russelll@netflix.com
